
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: nestjs-nextjs-auth-db
    ports:
      - '5432:5432'
    volumes:
      - pg-dataset:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-nextjsauth-backend
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pg-dataset: {}